const CATS=['All','Vehicles','Auto Parts','Tools','Furniture','Electronics','Outdoor','Farm','Clothing','Collectibles','Free','Other'];
const $=id=>document.getElementById(id);let sb,user=null,profile=null,listings=[],active='All',messageListing=null,staffTab='reports';
const clean=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=n=>Number(n)===0?'FREE':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
function toast(s){$('toast').textContent=s;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),3500)}
function openM(id){$(id).classList.remove('hidden');document.body.style.overflow='hidden'} function closeM(id){$(id).classList.add('hidden');document.body.style.overflow=''}
function configured(){return !WV_CONFIG.SUPABASE_URL.includes('PASTE_')&&!WV_CONFIG.SUPABASE_KEY.includes('PASTE_')}
async function init(){ $('year').textContent=new Date().getFullYear(); renderCats(); document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>closeM(x.dataset.close));
 if(!configured()){$('connectionStatus').textContent='Setup required: add your Supabase URL and publishable key to config.js.';toast('Open README-FIRST.md to connect the shared database.');return}
 sb=supabase.createClient(WV_CONFIG.SUPABASE_URL,WV_CONFIG.SUPABASE_KEY); const {data}=await sb.auth.getSession(); user=data.session?.user||null; await loadProfile(); await loadListings(); await updateUI();
 sb.auth.onAuthStateChange(async(_e,s)=>{user=s?.user||null;await loadProfile();await loadListings();await updateUI()});
 sb.channel('marketplace').on('postgres_changes',{event:'*',schema:'public',table:'listings'},loadListings).subscribe();
 $('connectionStatus').textContent='Connected. New posts appear on phones and computers.';
}
async function loadProfile(){profile=null;if(!user)return;const {data}=await sb.from('profiles').select('*').eq('id',user.id).single();profile=data}
async function loadListings(){if(!sb)return;const {data,error}=await sb.from('listings').select('*,profiles(display_name,banned)').eq('status','active').order('created_at',{ascending:false});if(error){toast(error.message);return}listings=data||[];renderListings()}
function renderCats(){const opts=CATS.map(c=>`<option value="${c}">${c==='All'?'All categories':c}</option>`).join('');$('categoryFilter').innerHTML=opts;$('formCategory').innerHTML=CATS.slice(1).map(c=>`<option>${c}</option>`).join('');$('categoryButtons').innerHTML=CATS.map(c=>`<button class="${c===active?'active':''}" data-cat="${c}">${c}</button>`).join('')}
function shown(){let q=$('searchInput').value.toLowerCase(),a=listings.filter(x=>(active==='All'||x.category===active)&&`${x.title} ${x.location} ${x.description} ${x.profiles?.display_name}`.toLowerCase().includes(q));let s=$('sortFilter').value;if(s==='price-low')a.sort((x,y)=>x.price-y.price);if(s==='price-high')a.sort((x,y)=>y.price-x.price);return a}
function renderListings(){const a=shown();$('listingCount').textContent=`${a.length} listing${a.length===1?'':'s'}`;$('emptyState').classList.toggle('hidden',a.length>0);$('listingGrid').innerHTML=a.map(x=>`<article class="listing-card"><div class="listing-image"><img src="${clean(x.image_urls?.[0]||'https://placehold.co/900x600/10253f/ffffff?text=No+Image')}"><span class="category-tag">${clean(x.category)}</span></div><div class="listing-body"><div class="listing-top"><h3>${clean(x.title)}</h3><div class="price">${money(x.price)}</div></div><div class="meta"><span>${clean(x.location)}</span><span>${clean(x.condition)}</span><span>Trade: ${clean(x.trade)}</span></div><p class="description">${clean(x.description)}</p><div class="card-footer"><div class="seller"><span>Seller</span><strong>${clean(x.profiles?.display_name||'User')}</strong></div>${user?.id===x.user_id?`<button class="delete-button" data-delete="${x.id}">Delete</button>`:`<button class="contact-btn" data-message="${x.id}">Private Message</button><button class="text-button" data-report="${x.id}">Report</button>`}</div></div></article>`).join('')}
async function updateUI(){$('accountButton').textContent=user?`${profile?.display_name||'Account'} • Sign Out`:'Sign In';$('staffButton').classList.toggle('hidden',!['staff','admin'].includes(profile?.role));if(profile?.banned)toast(`Your account is banned: ${profile.ban_reason||'Contact staff.'}`);await unread()}
function needUser(){if(!user){openM('authModal');return false}if(profile?.banned){toast('This account is banned.');return false}return true}
async function upload(files){if(files.length>5)throw Error('Choose no more than five images.');let urls=[];for(const f of files){if(f.size>5242880)throw Error(`${f.name} is larger than 5 MB.`);let path=`${user.id}/${crypto.randomUUID()}-${f.name.replace(/[^a-z0-9.]+/gi,'_')}`;let {error}=await sb.storage.from('listing-images').upload(path,f);if(error)throw error;urls.push(sb.storage.from('listing-images').getPublicUrl(path).data.publicUrl)}return urls}
async function unread(){if(!user||!sb)return;const {count}=await sb.from('messages').select('*',{count:'exact',head:true}).eq('recipient_id',user.id).is('read_at',null);$('messageBadge').textContent=count||0;$('messageBadge').classList.toggle('hidden',!count)}
async function inbox(){if(!needUser())return;const {data,error}=await sb.from('messages').select('*,sender:profiles!messages_sender_id_fkey(display_name),recipient:profiles!messages_recipient_id_fkey(display_name),listings(title)').or(`sender_id.eq.${user.id},recipient_id.eq.${user.id}`).order('created_at',{ascending:false});if(error)return toast(error.message);$('inboxList').innerHTML=data?.length?data.map(m=>`<div class="staff-row"><div><strong>${clean(m.sender_id===user.id?'To: '+m.recipient?.display_name:'From: '+m.sender?.display_name)}</strong><small>${clean(m.listings?.title||'Listing')} • ${new Date(m.created_at).toLocaleString()}</small><p>${clean(m.body)}</p></div>${m.sender_id!==user.id?`<button class="contact-btn" data-reply="${m.sender_id}" data-listing="${m.listing_id||''}">Reply</button>`:''}</div>`).join(''):'<div class="empty-state"><h3>No messages yet</h3></div>';await sb.from('messages').update({read_at:new Date().toISOString()}).eq('recipient_id',user.id).is('read_at',null);await unread();openM('inboxModal')}
async function staff(){if(!['staff','admin'].includes(profile?.role))return;let html='';if(staffTab==='users'){let {data}=await sb.from('profiles').select('*').order('created_at',{ascending:false});html=(data||[]).map(p=>`<div class="staff-row"><div><strong>${clean(p.display_name)}</strong><small>${p.role} • ${p.banned?'BANNED: '+clean(p.ban_reason||''): 'Active'}</small></div><button data-ban="${p.id}" data-state="${p.banned}">${p.banned?'Unban':'Ban'}</button></div>`).join('')}else if(staffTab==='posts'){let {data}=await sb.from('listings').select('id,title,location,profiles(display_name)').order('created_at',{ascending:false});html=(data||[]).map(l=>`<div class="staff-row"><div><strong>${clean(l.title)}</strong><small>${clean(l.profiles?.display_name)} • ${clean(l.location)}</small></div><button class="delete-button" data-staff-delete="${l.id}">Remove</button></div>`).join('')}else{let {data}=await sb.from('reports').select('*,listings(title),profiles:reporter_id(display_name)').eq('resolved',false).order('created_at',{ascending:false});html=(data||[]).map(r=>`<div class="staff-row"><div><strong>${clean(r.reason)}</strong><small>${clean(r.listings?.title||'Removed listing')} • ${clean(r.details||'No details')}</small></div><button data-resolve="${r.id}">Resolve</button></div>`).join('')} $('staffContent').innerHTML=html||'<div class="empty-state"><h3>Nothing here</h3></div>';openM('staffModal')}
$('accountButton').onclick=async()=>{if(user){await sb.auth.signOut();toast('Signed out.')}else openM('authModal')};$('authForm').onsubmit=async e=>{e.preventDefault();let action=e.submitter.value,email=$('authEmail').value,password=$('authPassword').value,name=$('authName').value.trim();let res=action==='signup'?await sb.auth.signUp({email,password,options:{data:{display_name:name}}}):await sb.auth.signInWithPassword({email,password});if(res.error)return toast(res.error.message);closeM('authModal');toast(action==='signup'?'Account created. Check your email if confirmation is enabled.':'Signed in.')};
['postButton','heroPostButton'].forEach(id=>$(id).onclick=()=>needUser()&&openM('postModal'));
$('imageInput').onchange=e=>{$('imagePreview').innerHTML=[...e.target.files].slice(0,5).map(f=>`<img src="${URL.createObjectURL(f)}">`).join('')};
$('listingForm').onsubmit=async e=>{e.preventDefault();if(!needUser())return;let b=e.submitter;b.disabled=true;b.textContent='Uploading…';try{let f=new FormData(e.target),urls=await upload([...$('imageInput').files]);let {error}=await sb.from('listings').insert({user_id:user.id,title:f.get('title'),price:+f.get('price'),category:f.get('category'),condition:f.get('condition'),location:f.get('location'),trade:f.get('trade'),description:f.get('description'),image_urls:urls});if(error)throw error;e.target.reset();$('imagePreview').innerHTML='';closeM('postModal');await loadListings();toast('Your listing is live for everyone.')}catch(err){toast(err.message)}finally{b.disabled=false;b.textContent='Publish Listing'}};
$('categoryButtons').onclick=e=>{let b=e.target.closest('[data-cat]');if(b){active=b.dataset.cat;$('categoryFilter').value=active;renderCats();renderListings()}};$('categoryFilter').onchange=e=>{active=e.target.value;renderCats();renderListings()};$('searchInput').oninput=renderListings;$('sortFilter').onchange=renderListings;
$('listingGrid').onclick=async e=>{let m=e.target.closest('[data-message]'),d=e.target.closest('[data-delete]'),r=e.target.closest('[data-report]');if(m&&needUser()){messageListing=listings.find(x=>x.id===m.dataset.message);$('messageTitle').textContent=`Message about ${messageListing.title}`;$('messageBody').value=`Hi, is the ${messageListing.title} still available?`;openM('messageModal')}if(d&&confirm('Delete this listing?')){let {error}=await sb.from('listings').delete().eq('id',d.dataset.delete);if(error)toast(error.message);else loadListings()}if(r&&needUser()){let reason=prompt('Why are you reporting this listing?');if(reason){let {error}=await sb.from('reports').insert({listing_id:r.dataset.report,reporter_id:user.id,reason});toast(error?error.message:'Report sent to staff.')}}};
$('messageForm').onsubmit=async e=>{e.preventDefault();let {error}=await sb.from('messages').insert({listing_id:messageListing.id,sender_id:user.id,recipient_id:messageListing.user_id,body:$('messageBody').value});if(error)return toast(error.message);closeM('messageModal');toast('Private message sent.')};$('messagesButton').onclick=inbox;$('inboxList').onclick=e=>{let b=e.target.closest('[data-reply]');if(b){messageListing={id:b.dataset.listing,user_id:b.dataset.reply,title:'listing'};closeM('inboxModal');$('messageTitle').textContent='Reply privately';$('messageBody').value='';openM('messageModal')}};
$('staffButton').onclick=staff;document.querySelector('.staff-tabs').onclick=e=>{let b=e.target.closest('[data-tab]');if(b){staffTab=b.dataset.tab;staff()}};$('staffContent').onclick=async e=>{let b=e.target.closest('[data-ban]'),d=e.target.closest('[data-staff-delete]'),r=e.target.closest('[data-resolve]');if(b){let banned=b.dataset.state==='true',reason=banned?null:prompt('Ban reason:','Marketplace rule violation');await sb.from('profiles').update({banned:!banned,ban_reason:reason}).eq('id',b.dataset.ban);staff()}if(d&&confirm('Remove listing?')){await sb.from('listings').delete().eq('id',d.dataset.staffDelete);staff();loadListings()}if(r){await sb.from('reports').update({resolved:true}).eq('id',r.dataset.resolve);staff()}};
init();
